### ISSUE TITLE
darkstat container error  "eth1: You don't have permission to capture on that device"

### ISSUE THREAD

**Issue by mahsanaru** [electrocucaracha/cFW-demo#1]
Hi,

We are trying to run the vFW_CNF_CDS scenario in the latest version Jakarta, but the vfw-1-vsn crashloops because of darkstat. The container shows the following error:

1: error: pcap_open_live(): eth1: You don't have permission to capture on that device (socket: Operation not permitted)

I would appreciate if you could guide us on how to fix this error.

Thanks and Regards,
Mahsa Monem

**Comment by mahsanaru** [comment]
It was already answered [here](https://jira.onap.org/browse/MULTICLOUD-1310). Sorry for the trouble. Thank you.

**Comment by electrocucaracha** [comment]
@mahsanaru thanks for reporting this issue, I realized that I need to update this code and add some CI tasks to keep it healthy

**Comment by electrocucaracha** [comment]
@mahsanaru I have upgraded the scripts and included some CI tasks for continuously testing changes. Hopefully these minimize the future errors.

**Comment by mahsanaru** [comment]
Great, Thank you very much.
